# Generated by Django 5.1.4 on 2025-01-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_op', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
