# Generated by Django 5.1.4 on 2025-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_op', '0004_rename_id_ordermodel_id_rename_id_productmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
