# Generated by Django 5.1.4 on 2025-01-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_op', '0005_alter_productmodel_id_alter_usermodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='Id',
            new_name='id',
        ),
    ]
