# Generated by Django 5.1.4 on 2025-01-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion_op', '0006_rename_id_productmodel_id_rename_id_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Product_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insertion_op.productmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='User_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insertion_op.usermodel'),
        ),
    ]
